"""
Report Agent — Agent 3 of InfraGPT

Receives both the TriageDiagnosis and RemediationPlan, then generates:
  1. Executive summary        (for stakeholders / Slack)
  2. Full post-mortem (RCA)   (structured incident report)
  3. PagerDuty / Slack alert  (copy-paste ready payload)
  4. Saves runbook entry      (to memory, for future agents)
"""

import time
from dataclasses import dataclass, field
from datetime import datetime
from typing import Generator
from memory.store import MemoryStore


@dataclass
class IncidentReport:
    incident_id: str
    title: str
    severity: str
    generated_at: str
    executive_summary: str
    timeline: list
    root_cause: str
    impact: str
    resolution_steps: list
    prevention: list
    slack_alert: str
    pagerduty_payload: dict

    def to_dict(self) -> dict:
        return {
            "incident_id": self.incident_id,
            "title": self.title,
            "severity": self.severity,
            "generated_at": self.generated_at,
            "executive_summary": self.executive_summary,
            "root_cause": self.root_cause,
            "impact": self.impact,
            "resolution_steps": self.resolution_steps,
            "prevention_count": len(self.prevention),
            "slack_alert": self.slack_alert,
        }


# ── Mock report templates per scenario ───────────────────────────────────────

MOCK_REPORTS = {
    "pod-crash": {
        "executive_summary": (
            "A production API pod (api-server-7d9f) entered CrashLoopBackOff at 09:41 UTC "
            "due to OOMKilled termination. The ML model loading process attempted to load 1.2 GB "
            "of weights into a container limited to 512 Mi, causing 14 crash-restart cycles over 2 hours. "
            "Node CPU spiked to 94%. Service was degraded. ETA to resolution: ~10 minutes via memory limit patch."
        ),
        "timeline": [
            "09:41:02 UTC — api-server-7d9f started, began loading ML model weights",
            "09:41:18 UTC — WARN: Memory at 85% (436Mi/512Mi)",
            "09:41:23 UTC — FATAL: OOMKilled (exit code 137) — restart #1",
            "09:41:30 UTC — Pod restart #2 (BackOff timer begins)",
            "10:15:00 UTC — InfraGPT alert triggered (14 restarts detected)",
            "10:15:03 UTC — Triage Agent: kubectl_get_pods → CrashLoopBackOff confirmed",
            "10:15:05 UTC — Triage Agent: kubectl_describe_pod → OOMKilled (exit 137)",
            "10:15:07 UTC — Triage Agent: kubectl_get_logs → ML model load (1.2GB) identified",
            "10:15:09 UTC — Triage Agent: check_node_cpu → 94% CRITICAL",
            "10:15:11 UTC — Remediation Agent: memory patch command generated",
            "10:25:00 UTC — Estimated: kubectl patch applied, rollout restart, pod Running",
        ],
        "impact": (
            "Service: API endpoint degraded — 100% of requests failing during crash loop. "
            "Duration: ~2 hours. Users affected: ~1,200 (production). "
            "SLA breach: Yes — exceeded 99.9% uptime threshold for the hour."
        ),
        "resolution_steps": [
            "Kill runaway Python process (pid 18432) on node-01",
            "Patch Deployment memory limit: 512Mi → 2Gi",
            "kubectl rollout restart deployment/api-server -n production",
            "Verify pod reaches Running state: kubectl rollout status",
            "Monitor for 15 minutes post-fix to confirm stability",
        ],
        "slack_alert": (
            ":rotating_light: *[InfraGPT ALERT]* Severity: HIGH\n"
            "*Incident:* API Pod CrashLoopBackOff — OOMKilled\n"
            "*Pod:* api-server-7d9f | *Node:* node-01 | *Namespace:* production\n"
            "*Root Cause:* ML model (1.2GB) exceeds 512Mi container limit\n"
            "*Fix:* Patch memory limit to 2Gi + rollout restart (~10 min)\n"
            "*Runbook:* <https://wiki/runbooks/oomkilled|OOMKilled Pod Runbook>\n"
            "_Generated by InfraGPT Report Agent_"
        ),
        "pagerduty_payload": {
            "routing_key": "INFRAGPT_PD_KEY",
            "event_action": "trigger",
            "payload": {
                "summary": "CRITICAL: api-server-7d9f CrashLoopBackOff (OOMKilled x14) — production",
                "severity": "error",
                "source": "InfraGPT",
                "component": "api-server",
                "group": "production",
                "class": "OOMKilled",
                "custom_details": {
                    "exit_code": 137,
                    "restarts": 14,
                    "node_cpu": "94%",
                    "memory_limit": "512Mi",
                    "fix_eta_mins": 10,
                },
            },
        },
    },
    "disk-pressure": {
        "executive_summary": (
            "Node node-02 reached 97% disk utilization, triggering Kubernetes DiskPressure taint. "
            "Pod scheduling was blocked on this node and running workloads were evicted. "
            "Root cause: 28 GB of unrotated pod logs and 41 GB of stale Docker overlay images. "
            "No log rotation policy was configured. Resolution involves docker prune + log cleanup (~20 min)."
        ),
        "timeline": [
            "08:00:00 UTC — Node disk passes 90% threshold (no alert configured)",
            "09:30:01 UTC — log-collector pod writes fail: 'No space left on device'",
            "09:35:00 UTC — Kubernetes applies DiskPressure taint to node-02",
            "09:35:30 UTC — log-collector-xk9p evicted",
            "09:40:00 UTC — New pod scheduling blocked on node-02",
            "09:42:00 UTC — InfraGPT alert triggered",
            "09:42:02 UTC — Triage Agent: check_disk → 97% CRITICAL, 3GB free",
            "09:42:04 UTC — Triage Agent: kubectl_get_pods → Evicted pods found",
            "09:42:06 UTC — Triage Agent: check_node_memory → RAM fine (38%)",
            "09:42:08 UTC — Remediation Agent: docker prune + log rotation plan generated",
        ],
        "impact": (
            "Node node-02 unavailable for scheduling. "
            "Evicted pods: log-collector-xk9p, metrics-server-9c2d. "
            "Cluster capacity reduced by ~33% (1 of 3 nodes). Duration: ongoing. "
            "Log data loss risk: High (no rotation configured)."
        ),
        "resolution_steps": [
            "docker system prune -af --volumes (on node-02) — frees ~41GB",
            "journalctl --vacuum-size=500M — frees ~11GB",
            "find /var/log/pods -name '*.log' -mtime +1 | xargs gzip — compresses old logs",
            "kubectl delete pod --field-selector=status.phase==Failed --all-namespaces",
            "Verify DiskPressure taint removed: kubectl describe node node-02",
        ],
        "slack_alert": (
            ":warning: *[InfraGPT ALERT]* Severity: HIGH\n"
            "*Incident:* Node Disk Pressure Critical\n"
            "*Node:* node-02 | *Disk:* 97% (3GB free)\n"
            "*Root Cause:* 28GB pod logs + 41GB Docker images (no rotation policy)\n"
            "*Fix:* docker prune + log vacuum (~20 min)\n"
            "*Impact:* Pod scheduling blocked, 2 workloads evicted\n"
            "_Generated by InfraGPT Report Agent_"
        ),
        "pagerduty_payload": {
            "routing_key": "INFRAGPT_PD_KEY",
            "event_action": "trigger",
            "payload": {
                "summary": "HIGH: node-02 DiskPressure at 97% — pod scheduling blocked",
                "severity": "error",
                "source": "InfraGPT",
                "component": "node-02",
                "group": "infrastructure",
                "class": "DiskPressure",
                "custom_details": {
                    "disk_percent": 97,
                    "free_gb": 3,
                    "evicted_pods": 2,
                    "fix_eta_mins": 20,
                },
            },
        },
    },
    "tf-drift": {
        "executive_summary": (
            "Terraform drift detected on the production S3 model registry bucket. "
            "Three critical security controls were manually disabled via AWS console: "
            "versioning suspended, public access unblocked, and encryption removed. "
            "This is a CRITICAL security incident — the bucket was publicly exposed "
            "with unencrypted data. Immediate terraform apply required."
        ),
        "timeline": [
            "Unknown time — Manual AWS console changes made (CloudTrail audit required)",
            "07:00:00 UTC — CI pipeline runs terraform plan (-detailed-exitcode)",
            "07:00:05 UTC — Exit code 2: 3 resource drifts detected",
            "07:00:06 UTC — InfraGPT alert triggered",
            "07:00:07 UTC — Triage Agent: terraform_plan → 3 drifts confirmed",
            "07:00:09 UTC — Triage Agent: terraform_apply_preview → safe to apply",
            "07:00:11 UTC — Remediation Agent: emergency block-public-access AWS CLI command",
            "07:00:13 UTC — Remediation Agent: terraform apply plan generated",
            "07:05:00 UTC — Estimated: terraform apply complete, state reconciled",
        ],
        "impact": (
            "S3 bucket mlops-model-registry-bucket-prod-xyz publicly exposed. "
            "Data at rest: UNENCRYPTED. Model version history: DISABLED (rollback impossible). "
            "Regulatory risk: GDPR/SOC2 compliance breach. "
            "Duration of exposure: Unknown (requires CloudTrail investigation)."
        ),
        "resolution_steps": [
            "IMMEDIATE: aws s3api put-public-access-block (block all public access)",
            "IMMEDIATE: aws s3api put-bucket-encryption (re-enable AES256)",
            "terraform apply -auto-approve (restore all 3 drifted resources)",
            "Audit CloudTrail: identify who made manual changes and when",
            "Rotate any credentials that may have been exposed",
            "File security incident report with compliance team",
        ],
        "slack_alert": (
            ":fire: *[InfraGPT CRITICAL ALERT]* Severity: CRITICAL\n"
            "*Incident:* Terraform State Drift — Security Controls Disabled\n"
            "*Resource:* mlops-model-registry-bucket-prod-xyz\n"
            "*Drifts:* Public access OPEN :x: | Encryption REMOVED :x: | Versioning OFF :x:\n"
            "*Action Required:* terraform apply + CloudTrail audit IMMEDIATELY\n"
            "*Fix ETA:* ~15 min\n"
            "@security-team @infra-on-call\n"
            "_Generated by InfraGPT Report Agent_"
        ),
        "pagerduty_payload": {
            "routing_key": "INFRAGPT_PD_KEY",
            "event_action": "trigger",
            "payload": {
                "summary": "CRITICAL: S3 bucket publicly exposed, encryption removed — terraform drift",
                "severity": "critical",
                "source": "InfraGPT",
                "component": "mlops-model-registry-bucket-prod-xyz",
                "group": "security",
                "class": "TerraformDrift",
                "custom_details": {
                    "drifts_detected": 3,
                    "public_access": "OPEN",
                    "encryption": "DISABLED",
                    "versioning": "SUSPENDED",
                    "fix_eta_mins": 15,
                },
            },
        },
    },
}


class ReportAgent:
    """
    Agent 3: Generates post-mortem, executive summary, and alert payloads
    from the combined Triage + Remediation output.
    """

    def __init__(self, memory: MemoryStore):
        self.memory = memory

    def generate_report(self, incident: dict, diagnosis, plan) -> Generator:
        """Yields streaming events: building → sections → report → done."""

        sid = incident.get("id", "pod-crash")
        title = incident.get("title", "Infrastructure Incident")
        generated_at = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")

        yield {"type": "status", "msg": "📊 Report Agent generating post-mortem..."}
        time.sleep(0.4)

        yield {"type": "status", "msg": "✍️  Building executive summary..."}
        time.sleep(0.3)

        raw = MOCK_REPORTS.get(sid, {
            "executive_summary": f"Incident '{title}' triaged and remediated by InfraGPT. See findings below.",
            "timeline": ["Incident detected", "Triage complete", "Remediation plan generated"],
            "impact": "See triage findings for impact details.",
            "resolution_steps": plan.immediate_steps[:3] if plan else [],
            "slack_alert": f":rotating_light: *[InfraGPT]* {title} — {diagnosis.severity}",
            "pagerduty_payload": {"summary": title, "severity": diagnosis.severity.lower()},
        })

        yield {"type": "status", "msg": "📅 Assembling incident timeline..."}
        time.sleep(0.3)

        yield {"type": "status", "msg": "📣 Generating Slack & PagerDuty alerts..."}
        time.sleep(0.3)

        import uuid
        incident_id = f"INC-{uuid.uuid4().hex[:6].upper()}"

        report = IncidentReport(
            incident_id=incident_id,
            title=title,
            severity=diagnosis.severity,
            generated_at=generated_at,
            executive_summary=raw["executive_summary"],
            timeline=raw["timeline"],
            root_cause=diagnosis.root_cause,
            impact=raw["impact"],
            resolution_steps=raw["resolution_steps"],
            prevention=plan.prevention if plan else [],
            slack_alert=raw["slack_alert"],
            pagerduty_payload=raw["pagerduty_payload"],
        )

        yield {
            "type": "report",
            "report": report.to_dict(),
            "object": report,
            "slack_alert": report.slack_alert,
            "pagerduty_payload": report.pagerduty_payload,
            "timeline": report.timeline,
        }

        yield {"type": "status", "msg": f"✅ Report {incident_id} generated — ready for Loom / Confluence"}
